// <auto-generated />
using System;
using Bolika_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bolika_API.Migrations
{
    [DbContext(typeof(DbCharacters))]
    partial class DbCharactersModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Bolika_API.Characters", b =>
                {
                    b.Property<int>("CharId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("CharRole")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatisticId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharId");

                    b.HasIndex("StatisticId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Bolika_API.SkillLists", b =>
                {
                    b.Property<int>("SkillListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterCharId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SkillListId");

                    b.HasIndex("CharacterCharId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillLists");
                });

            modelBuilder.Entity("Bolika_API.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cst")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dmg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Img")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Bolika_API.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Atk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Def")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eng")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spd")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Bolika_API.Characters", b =>
                {
                    b.HasOne("Bolika_API.Statistics", "Statistic")
                        .WithMany()
                        .HasForeignKey("StatisticId");

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("Bolika_API.SkillLists", b =>
                {
                    b.HasOne("Bolika_API.Characters", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterCharId");

                    b.HasOne("Bolika_API.Skills", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });
#pragma warning restore 612, 618
        }
    }
}
